### ISSUE TITLE
emscripten

### ISSUE THREAD

**Issue by bquenin** [aevum/libgdx-cpp#38]
More a question than an issue.

Do you guys know about emscripten, https://github.com/kripken/emscripten/wiki ? A C++ to JavaScript cross compiler.

Is it something you would consider as a potential backend for libgdx-cpp ?

Thanks

**Comment by pedroarroyo** [comment]
Did anything ever come of this?

**Comment by scooterman** [comment]
Hey @pedroarroyo, I did make some progress but the project lost traction so I didn't finished it :disappointed:.

**Comment by Murii** [comment]
@scooterman please continue your work on libgdx-cpp.If it's possible please add a cmake build system because the current one I have not managed to make it work on my Linux machine(Ubuntu 14.04)

**Comment by scooterman** [comment]
@Murii, what's happening with cmake? Please open a new issue so I can try to fix it for you
