### ISSUE TITLE
Error building on Ubuntu 

### ISSUE THREAD

**Issue by Murii** [aevum/libgdx-cpp#42]
/home/muresan/libgdx-cpp/src/gdx-cpp/graphics/g3d/model/still/StillModel.cpp: In member function ‘virtual std::vector<gdx::SubMesh*>& gdx::StillModel::getSubMeshes() const’:
/home/muresan/libgdx-cpp/src/gdx-cpp/graphics/g3d/model/still/StillModel.cpp:90:34: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     return ( vector<SubMesh*>& ) subMeshes;
                                  ^
cc1plus: all warnings being treated as errors
make[2]: *** [src/gdx-cpp/CMakeFiles/gdx-cpp.dir/graphics/g3d/model/still/StillModel.cpp.o] Error 1
make[1]: *** [src/gdx-cpp/CMakeFiles/gdx-cpp.dir/all] Error 2
make: *** [all] Error 2
 
While running cmake install !

**Comment by scooterman** [comment]
Hey @Murii, this error was due a flag that was treating all warnings as errors. I've commented the flag, it should build by now.

**Comment by Murii** [comment]
Thanks! I'll let you know what happens.

**Comment by Murii** [comment]
It finished without any probles,thanks!
